"use client"

// import type { Metadata } from "next"
import localFont from "next/font/local"
import "./globals.css"
import { Menu, MenuDev } from "@/components"

// Load custom font //
const font = localFont({
	variable: "--font-primary",
	src: [
		{
			path: "../../public/fonts/PPSupplySans-Regular.otf",
			weight: "400",
		},
		{
			path: "../../public/fonts/PPSupplySans-Ultralight.otf",
			weight: "200",
		},
	],
})

// export const metadata: Metadata = {
// 	title: "Create Next App",
// 	description: "Generated by create next app",
// }

function Overlay() {
	return (
		<div className='absolute top-0 left-0 z-50 w-full h-full pointer-events-none'>
			<a href='https://juliscapucin.com/' className='absolute left-8 bottom-8'>
				<span className='bg-colorBlack'>JULI SCAPUCIN</span>
				<br />
				<span className='bg-colorBlack'>CREATIVE DEVELOPER</span>
			</a>
			<div className='absolute bottom-8 right-8 bg-colorBlack'>2023/2024</div>
		</div>
	)
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${font.className} font-light text-colorGreen bg-colorBlack`}
			>
				{children}
				<Overlay />
			</body>
		</html>
	)
}
